---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ${VAGRANT_DEFAULT_BOX:-generic/rhel7}
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 9200, host: 9200"
      - "vm.network 'forwarded_port', guest: 5601, host: 5601"
    groups:
      - elasticsearch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
  inventory:
    group_vars:
      elasticsearch:
        ca_crt: ../resources/ca/ca.crt
    host_vars:
      instance:
        server_crt: ../resources/instance/instance.crt
        server_key: ../resources/instance/instance.key
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
